name: Discord Release Notifications

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Release Msg
        run: |
          
          MESSAGE="New version released: ${{ github.event.release.name }} - ${{ github.event.release.html_url }}"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\":\"$MESSAGE\"}" \
          ${{ secrets.DISCORD_RELEASE_WEBHOOK }}